"""Initial migration

Revision ID: 6e415917e242
Revises: 89671bf63f99
Create Date: 2025-05-30 09:15:41.571782

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6e415917e242'
down_revision = '89671bf63f99'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('doctor')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('doctor',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), nullable=False),
    sa.Column('specialization', sa.VARCHAR(length=100), nullable=False),
    sa.Column('experience', sa.INTEGER(), nullable=False),
    sa.Column('photo', sa.VARCHAR(length=200), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
