"""delete photo

Revision ID: 89671bf63f99
Revises: ebf51c982322
Create Date: 2025-05-30 00:47:57.732262

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '89671bf63f99'
down_revision = 'ebf51c982322'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('photo')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('photo', sa.VARCHAR(length=200), nullable=True))

    # ### end Alembic commands ###
