"""Add Doctor table

Revision ID: db7642679b87
Revises: 60b170dc0e25
Create Date: 2025-05-02 00:04:16.707826

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'db7642679b87'
down_revision = '60b170dc0e25'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('doctor', schema=None) as batch_op:
        batch_op.alter_column('specialization',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
        batch_op.alter_column('experience',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('photo',
               existing_type=sa.VARCHAR(length=200),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('doctor', schema=None) as batch_op:
        batch_op.alter_column('photo',
               existing_type=sa.VARCHAR(length=200),
               nullable=True)
        batch_op.alter_column('experience',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('specialization',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)

    # ### end Alembic commands ###
